### ISSUE TITLE
Incorrect bin centre on rebinning time-differential runs

### ISSUE THREAD

**Issue by rmlmcfadden** [dfujim/bdata#8]
For a time-differential run with <i>n</i> bins, I expect that, upon rebinning using a number <i>b</i> that is also a factor of <i>n</i>, to get a new bin centre (for the first time bin) that is a <i>b</i> times larger than in the ubinned case.

Simple reproducer:

```python
import bdata as bd
from numpy.testing import assert_approx_equal

data = bd.bdata(45514, year=2013)

binning = 10

t0_unbinned = data.asym("c", rebin=1)[0][0]  # 0.005
t0_binned = data.asym("c", rebin=binning)[0][0]  # 0.045!?

assert_approx_equal(t0_binned, t0_unbinned * binning)
```
In this case, if there are 10 times fewer bins (i.e., each bin is 10 times as wide), the centre position (of the first bin) should just scale by a factor of 10 from the unbinned case.

**Comment by dfujim** [comment]
Good catch! There was an off-by-one error in both the rebinning of the times and the asymmetries. So `rebin=10` was actually `rebin=9`. Fixed in f265265cfadb7b4ca3c5876f5b3c53ddca0926fa
