### ISSUE TITLE
[feature request] helper functions for calculating the magnetic field & its uncertainty

### ISSUE THREAD

**Issue by rmlmcfadden** [dfujim/bdata#9]
Just like how `bdata` has data members/functions to store/calculate the beam energy, it would be convenient to have equivalent functionality for the applied magnetic field.

I see that this is currently handled through `bfit` - was there a particular reason the calculation was decoupled from the `bdata` class?

**Comment by dfujim** [comment]
Not really. More likely was that I was working on the graphical calculator interface and needed the conversion functions, so that's where they ended up. Probably the DAC to attenuation calculations should also be ported over.

**Comment by dfujim** [comment]
Added in 75904ebc718fba6225cb1ba81a167fd2f150a4ce
